import type { FC, ReactElement } from "react";
import Head from "next/head";
import Header from "./header";

const Layout: FC<{
  children: ReactElement | ReactElement[];
  title: string;
}> = ({ children, title }) => {
  return (
    <body className="mx-auto grid min-h-screen w-[86%] gap-10">
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="devchallenges.png" />
      </Head>
      <Header />
      <main className="min-h-main">{children}</main>
    </body>
  );
};

export default Layout;
