import type { FC, ReactElement } from "react";
import Head from "next/head";
import Header from "./header";

const Layout: FC<{
  children: ReactElement | ReactElement[];
  title: string;
}> = ({ children, title }) => {
  return (
    <div className="flex min-h-screen flex-col gap-10 px-20">
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="devchallenges.png" />
      </Head>
      <Header />
      <main className="">{children}</main>
    </div>
  );
};

export default Layout;
