import type { FC, ReactElement } from "react";
import Head from "next/head";
import Header from "./header";
import { useContext } from "react";
import { ModalContext } from "../context/modalContext";
import Modal from "./modal";
import { signOut } from "next-auth/react";

const Layout: FC<{
  children: ReactElement | ReactElement[];
  title: string;
}> = ({ children, title }) => {
  const { modalView } = useContext(ModalContext);
  return (
    <div className="flex min-h-screen flex-col gap-10 px-8 md:px-20">
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="devchallenges.png" />
      </Head>
      <Header />
      <main className="">
        {children}
        <LogOut />
      </main>
      {modalView ? <Modal /> : <div></div>}
    </div>
  );
};

const LogOut = () => (
  <button
    onClick={() => {
      signOut().catch((err) => console.error(err));
    }}
    className="absolute bottom-8 right-8 rounded-xl border py-3 px-5 shadow-lg"
  >
    Log Out
  </button>
);

export default Layout;
